# Generated by Django 3.0.5 on 2020-05-05 05:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=50)),
                ('original_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('alt_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('cover', models.CharField(max_length=255)),
                ('descriptions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('publication_status', models.CharField(max_length=100)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
            ],
            options={
                'db_table': 'title',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('num_major', models.PositiveIntegerField()),
                ('num_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('pages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='pytaku_web.Title')),
            ],
            options={
                'db_table': 'chapter',
                'ordering': ['num_major', 'num_minor'],
            },
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('title', 'num_major', 'num_minor'), name='unique_number_within_title'),
        ),
    ]
