# Generated by Django 3.0.5 on 2020-05-24 11:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=1024)),
                ('method', models.CharField(max_length=7)),
                ('headers', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('body', models.TextField()),
                ('resp_body', models.TextField()),
                ('resp_status', models.IntegerField()),
            ],
            options={
                'db_table': 'scrape_attempt',
            },
        ),
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(choices=[('Scrape', 'scrape')], max_length=100)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'task_queue',
            },
        ),
    ]
