# Generated by Django 3.0.5 on 2020-05-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytaku_scraper', '0002_auto_20200524_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskqueue',
            name='name',
            field=models.CharField(choices=[('Download', 'download')], max_length=100),
        ),
        migrations.AddConstraint(
            model_name='taskqueue',
            constraint=models.UniqueConstraint(fields=('name', 'payload'), name='unique_url_payload'),
        ),
    ]
