# Generated by Django 3.0.5 on 2020-05-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pytaku_scraper', '0003_auto_20200524_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadresult',
            old_name='created_at',
            new_name='downloaded_at',
        ),
    ]
